"""Fixing database schema mismatch

Revision ID: 003ba55c8eac
Revises: 80615240a8c1
Create Date: 2025-03-03 16:51:06.069734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003ba55c8eac'
down_revision = '80615240a8c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('call_type', sa.String(length=50), nullable=True),
    sa.Column('customer', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('schedule', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ScheduledReport')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('account_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('customer_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('serial_number',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('service_location',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('region',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('technician_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('technician_email',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('asset_Description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('contract_expiry_date',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['serial_number'])

    with op.batch_alter_table('spare_req', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('serial_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('asset_Description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('technician_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('foc_no',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('customer_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('service_location',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('region',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('contract',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('contract_expiry_date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('product_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('yield_achvd',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('spare_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('warehouse',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('any_remarks',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('warranty_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('warranty_remarks',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('spares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('currency', sa.String(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('material_nr',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('material_desc',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
        batch_op.drop_column('Currency')
        batch_op.drop_column('Brand')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('service_location',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('asset_Description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('called_by',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('region',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('remaining_time',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.drop_column('technecian_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('technecian_email', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('remaining_time',
               existing_type=sa.String(length=1000),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('region',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('called_by',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('asset_Description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('service_location',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)

    with op.batch_alter_table('spares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Brand', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('Currency', sa.TEXT(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
        batch_op.alter_column('material_desc',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('material_nr',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('currency')
        batch_op.drop_column('brand')

    with op.batch_alter_table('spare_req', schema=None) as batch_op:
        batch_op.alter_column('warranty_remarks',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('warranty_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('any_remarks',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('warehouse',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('spare_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('yield_achvd',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('product_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('contract_expiry_date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('contract',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('region',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('service_location',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('customer_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('foc_no',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('technician_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('asset_Description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('serial_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('contract_expiry_date',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('asset_Description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('technician_email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('technician_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('region',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('service_location',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('serial_number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('customer_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('account_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('ScheduledReport',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('report_type', sa.TEXT(), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('period', sa.TEXT(), nullable=True),
    sa.Column('technician_id', sa.INTEGER(), nullable=True),
    sa.Column('region', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('call_type', sa.TEXT(), nullable=True),
    sa.Column('customer', sa.TEXT(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('schedule', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('scheduled_report')
    # ### end Alembic commands ###
