"""Initial full user permissions

Revision ID: d447d7a9b104
Revises: 
Create Date: 2025-04-16 12:00:11.793840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd447d7a9b104'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('Delivery_Team', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        #batch_op.alter_column('id',
               #existing_type=sa.INTEGER(),
               #nullable=False,
              # autoincrement=True)
        #batch_op.drop_column('Name')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('account_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('customer_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('serial_number',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('service_location',
               existing_type=sa.BLOB(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('region',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('technician_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('technician_email',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('asset_Description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('contract_expiry_date',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('last_pm_date',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('pm_freq',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('install_date',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('asset_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('part_no',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['serial_number'])
        batch_op.drop_column('pm_due_date')

    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('cust_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('cust_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('contract_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('durations',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('contract_start_date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('contract_end_date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('mono_commitment',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('mono_charge',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('mono_excess_charge',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('color_commitment',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('color_charge',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('color_excess_charge',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('rental_charges',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('software_rental',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('billing_cycle',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('contract_currency',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('Billing currency',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('billing_company',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('sales_person',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('document_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['contract_code'])
        batch_op.create_foreign_key(None, 'cust', ['cust_code'], ['cust_code'])

    with op.batch_alter_table('cust', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('cust_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('cust_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('billing_company',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['cust_name'])

    with op.batch_alter_table('mc_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('part_no', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Text(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_column('asset_Description')
        batch_op.drop_column('Part_No')
        batch_op.drop_column('Price')

    with op.batch_alter_table('spare_req', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('serial_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('asset_Description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('technician_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('foc_no',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('customer_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('service_location',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('region',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('contract',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('contract_expiry_date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('product_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('yield_achvd',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('spare_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('warehouse',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('any_remarks',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('warranty_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('warranty_remarks',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('request_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.drop_column('date_fixed')

    with op.batch_alter_table('spares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('currency', sa.String(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('material_nr',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('material_desc',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
        batch_op.drop_column('Brand')
        batch_op.drop_column('Currency')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('service_location',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('asset_Description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('called_by',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('region',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('remaining_time',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.drop_column('technecian_email')

    with op.batch_alter_table('toner_costing', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('toner_model',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('toner_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('unit_cost',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('toner_models', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('asset_model',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('part_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('machine_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('tk_k',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('k_life',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('tk_c',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('c_life',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('tk_m',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('m_life',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('tk_y',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('y_life',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('toner_request', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('serial_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('toner_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('toner_model',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('can_add_user', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_edit_user', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_delete_user', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_assign_roles', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_tickets', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_create_tickets', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_edit_tickets', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_close_tickets', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_assign_tickets', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_technicians', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_add_technicians', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_edit_technicians', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_assets', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_add_assets', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_edit_assets', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_delete_assets', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_contracts', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_add_contracts', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_edit_contracts', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_delete_contracts', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_request_toner', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_edit_toner_requests', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_toner_dashboard', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_delete_toner_request', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_request_spares', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_spare_dashboard', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_delete_spare_request', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_reports', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_export_data', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_financials', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_export_financials', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_schedule_pm', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_pm_dashboard', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_access_settings', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_upload_documents', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_audit_logs', sa.Boolean(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.drop_column('can_view_audit_logs')
        batch_op.drop_column('can_upload_documents')
        batch_op.drop_column('can_access_settings')
        batch_op.drop_column('can_view_pm_dashboard')
        batch_op.drop_column('can_schedule_pm')
        batch_op.drop_column('can_export_financials')
        batch_op.drop_column('can_view_financials')
        batch_op.drop_column('can_export_data')
        batch_op.drop_column('can_view_reports')
        batch_op.drop_column('can_delete_spare_request')
        batch_op.drop_column('can_view_spare_dashboard')
        batch_op.drop_column('can_request_spares')
        batch_op.drop_column('can_delete_toner_request')
        batch_op.drop_column('can_view_toner_dashboard')
        batch_op.drop_column('can_edit_toner_requests')
        batch_op.drop_column('can_request_toner')
        batch_op.drop_column('can_delete_contracts')
        batch_op.drop_column('can_edit_contracts')
        batch_op.drop_column('can_add_contracts')
        batch_op.drop_column('can_view_contracts')
        batch_op.drop_column('can_delete_assets')
        batch_op.drop_column('can_edit_assets')
        batch_op.drop_column('can_add_assets')
        batch_op.drop_column('can_view_assets')
        batch_op.drop_column('can_edit_technicians')
        batch_op.drop_column('can_add_technicians')
        batch_op.drop_column('can_view_technicians')
        batch_op.drop_column('can_assign_tickets')
        batch_op.drop_column('can_close_tickets')
        batch_op.drop_column('can_edit_tickets')
        batch_op.drop_column('can_create_tickets')
        batch_op.drop_column('can_view_tickets')
        batch_op.drop_column('can_assign_roles')
        batch_op.drop_column('can_delete_user')
        batch_op.drop_column('can_edit_user')
        batch_op.drop_column('can_add_user')
        batch_op.drop_column('role')

    with op.batch_alter_table('toner_request', schema=None) as batch_op:
        batch_op.alter_column('toner_model',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('toner_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('serial_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('toner_models', schema=None) as batch_op:
        batch_op.alter_column('y_life',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('tk_y',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('m_life',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('tk_m',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('c_life',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('tk_c',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('k_life',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('tk_k',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('machine_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('part_number',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('asset_model',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('toner_costing', schema=None) as batch_op:
        batch_op.alter_column('unit_cost',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('toner_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('toner_model',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('technecian_email', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('remaining_time',
               existing_type=sa.String(length=1000),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('region',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('called_by',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('asset_Description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('service_location',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('spares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Currency', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('Brand', sa.TEXT(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
        batch_op.alter_column('material_desc',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('material_nr',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('currency')
        batch_op.drop_column('brand')

    with op.batch_alter_table('spare_req', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_fixed', sa.DATE(), nullable=True))
        batch_op.alter_column('request_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('warranty_remarks',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('warranty_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('any_remarks',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('warehouse',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('spare_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('yield_achvd',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('product_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('contract_expiry_date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('contract',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('region',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('service_location',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('customer_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('foc_no',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('technician_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('asset_Description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('serial_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('mc_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Price', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('Part_No', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('asset_Description', sa.TEXT(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('price')
        batch_op.drop_column('part_no')
        batch_op.drop_column('asset_description')

    with op.batch_alter_table('cust', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('billing_company',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('cust_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('cust_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('document_path',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('sales_person',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('billing_company',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('Billing currency',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('contract_currency',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('billing_cycle',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('software_rental',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('rental_charges',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('color_excess_charge',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('color_charge',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('color_commitment',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('mono_excess_charge',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('mono_charge',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('mono_commitment',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('contract_end_date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('contract_start_date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('durations',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('contract_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('cust_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('cust_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pm_due_date', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('department',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('part_no',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('asset_status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('install_date',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('pm_freq',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('last_pm_date',
               existing_type=sa.String(length=100),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('contract_expiry_date',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('asset_Description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('technician_email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('technician_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('region',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('service_location',
               existing_type=sa.String(length=255),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('serial_number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('customer_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('account_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('Delivery_Team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Name', sa.TEXT(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
